# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3751d6fab757429731c6462418d5a776dfa7fd33a97f9df358170dba9558636fb0b1233803261053842e7d00bd1affc617562ae4a697eb70e6ddc5b3db3d5f3c

test:
  secret_key_base: a6405876d6610d91f6f40fa80a1d9ed066bb7039fa58c31be7ef6478e5dd1334d71fc8e2cb2ff08fef69d0ccb88be413d48375c7f04848231e932affd2ff9a6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
